name: chemml
channels:
    - conda-forge
dependencies:
    - python=3.12
    - sphinx
    - sphinx_rtd_theme
    - sphinx-automodapi
      # chemml depends
    - tensorflow
    - pip:
        - nbsphinx



channels:
    - openbabel

dependencies:
    - openbabel

