name: chemml
channels:
    - conda-forge
    - openbabel
dependencies:
    - python=3.12
    - pip
    - sphinx
    - sphinx_rtd_theme
    - sphinx-automodapi
    - nbsphinx 
      # chemml depends
    - tensorflow
    - openbabel


